version: '3'
networks: 
  workers:
services:
  consumer01:
    build: .
    env_file: ./.env
    command: node ./index
    networks:
      - workers
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  consumer02:
    build: .
    env_file: ./.env
    command: node ./index
    networks:
      - workers
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules